### ISSUE TITLE
Parse feature service queries before requesting feature from the database

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop#183]
### Concept

As a user, I see faster performance on the following queries:
1. FeatureServer
2. FeatureServer/0
3. FeatureServer/query?where=1=1&returnCountOnly=true
4. FeatureServer/query?where=1=1&returnIdsOnly=true
5. FeatureServer/0/query?where=1=1&outStatistics=[{"statisticType":"max","onStatisticField":"objectId","outStatisticFieldName":%20"max_id"}]

These queries should make the smallest possible queries to the features in the database and make use of caching for queries that do not change once the data is cached.
### Query mapping

:construction:

**Comment by chelm** [comment]
I was thinking it'd be cool to pull @ngoldman into this work. We can explain why we need this and can use it as way to get him more engaged.

**Comment by chelm** [comment]
This will basically be a refactor of the `lib/BaseController` featureservice logic - sorely need too.

**Comment by chelm** [comment]
The big issue here is that koop providers get all the features it needs from the DB THEN is passes those to the centralized FeatureServer code in koop. This breaks down with large data (>100k features) as the size of the data we pass around is too big. 

So the solution is to get smarter about parsing `req.params` and `req.query` prior to hitting the DB in the provider. So I think the central BaseController gets a lot smarter about what queries is needs to make.  

Just breaking this down into what would happen and where: 

1. FeatureServer 
* Get data extent from DB instead of every feature

2. FeatureServer/0
* Get data extent from DB instead of every feature

3. FeatureServer/query?where=1=1&returnCountOnly=true
* devoid of many other query params when: where is either not defined or equals 1=1 and returnCountOnly is true, then we just need to get the count from the db and send it back

4. FeatureServer/query?where=1=1&returnIdsOnly=true
* Same as 3, except we need to get all the ids from the DB 

5. FeatureServer/0/query?where=1=1&outStatistics=[{"statisticType":"max","onStatisticField":"objectId","outStatisticFieldName":%20"max_id"}]
* The big question here is how do we drop these queries down to the DB instead of processing theses in memory. I think this is a story on its own.

**Comment by chelm** [comment]
Been thinking a lot about this lately. My current thoughts are around having the lib/BaseController have a new method called some thing like "parseRequest".  This method will take a request object and correct parse out the params and query string and return an array of special known "keywords" that providers can key off to issue requests for data. These keywords be something like: 

* features
* extent
* fields 
* count
* statistics 

A provider would get these keywords back and get each one from the Cache before calling processFeatureServer with any data. this was the code in processFeatureService can cleanly react to what it been given. For instance if its a request for `FeatureServer/0` it needs only the "extent" and "fields", and not every single feature. This will be faster when tables are huge (1mm rows).

**Comment by dmfenton** [comment]
@chelm I think that sounds about right. In Koop-Socrata I use a method called featureServer to act as a dispatch that parses the request sends to separate methods for either features or count. I think it's pretty clean.

https://github.com/koopjs/koop-socrata/blob/master/controller/index.js#L144-L165

**Comment by chelm** [comment]
@dmfenton Yes its clean for socrata but I'd like prevent each provider from having to implement that same logic over and over. The real tricky part is that each provider will also request data with a different set of params or table structure. 

But actually as I just wrote that I bet I could just have the providers send along a table name. Then the base controller could parse everything from the request AND get the data it needed. yes that will probably be cleaner and a smaller change to how providers already work.

**Comment by dmfenton** [comment]
Totally agreed that this logic should sit in base controller. Providers shouldn't have to implement any feature service logic at all.

**Comment by dmfenton** [comment]
This is OBE. Caches and providers will be responsible for passing the right data back to featureServer.
