### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop#228]
`Koop.Logger` should have standard patterns (log lines from koop should be recognizable as coming from koop) and levels (info, error, debug) and always prepend a timestamp.

Also was discussing with @chelm a while back the challenge of how to allow different parts of koop to use the logger, and I think I found the solution: don't! I think the best way is for koop's submodules to emit log events and for the logger to listen for them. So basically my recommendation would be to implement an event handler where koop manages events and passes them to relevant places, and submodules don't know anything about each other and just emit events using the native node [EventEmitter](https://nodejs.org/api/events.html). This would clean up a lot of logic and allow for us to decouple more things down the line (like plugin & provider issues, see https://github.com/koopjs/koop/issues/225#issuecomment-127684645).

**Comment by ngoldman** [comment]
(EE pattern would make it easier to not pass the entire `koop` instance into every new model)

**Comment by ngoldman** [comment]
So `koop.Logger` is a customized instance of [`winston.Logger`](https://github.com/winstonjs/winston), which supports levels and colorization and other standard stuff. Timestamps are being prepended when writing log files in production but not when simply printing out to console in development.

I had a conversation with @kpettijohn a while back about the notion that koop shouldn't necessarily be writing its own logs. In a properly contained environment it should be fairly easy to pipe all log events to stdout and stderr and have another service parse that into log files rather than leaving it up to koop's log implementation.

I also think there's a lot we're not logging that we should be. @jwieringa are we capturing regular request events (GET/POST to route, stuff like that) in production? Should we be? I don't get the impression that we're currently capturing a lot.

**Comment by dmfenton** [comment]
We're capturing those events because Koop runs behind NGINX in production. They're definitely handy to have around. I agree that Koop should be able to pipe its log events rather than writing it's own logs. It doesn't make sense to log in multiple places on the file system. Koop workers still need to be able to write their own logs, however.

**Comment by ajturner** [comment]
stdout -> fluentd ?

**Comment by kpettijohn** [comment]
+1 for stderr + stdout

It will help provide flexibility/constancy when working with log capturing applications/services.

Also it would be nice to have control over the log level (debug, info...etc.) and log local (local0, local1...etc.) using environment variables/configuration file.

**Comment by ngoldman** [comment]
Some work needs to be done in terms of actually using the `koop.log` instance that koop passes around instead of `console.log|warn|error`, both in koop and its plugins. From that point writing to stderr & stdout and controlling log levels via env vars or config would be more straightforward.

**Comment by kpettijohn** [comment]
@dmfenton just curious but whats forcing the koop workers to keep writing their own logs?

**Comment by dmfenton** [comment]
Nothing forces it, but they are running in totally separate processes on separate machines. So either they communicate their log events back to the main app (which seems hard) or they write their own.

**Comment by ajturner** [comment]
Perhaps we're talking around the question.

Workers m don't need to 'write' their own log to local disk files - just output their logs using [standard streams](https://en.m.wikipedia.org/wiki/Standard_streams) (not to be confused with [node stream](https://en.m.wikipedia.org/wiki/Node_stream))

Once in the standard stream, Aggregation and storage can occur through dozens of standard mechanisms.

**Comment by dmfenton** [comment]
@ajturner Good point. That encapsulates the issue well.

**Comment by chelm** [comment]
Hi! I think making koop.log dump everything to stdout or stderr would rock. The work seems like it'd be in `lib/Logger.js` and maintaining support for a similar interface to what Winston expects (.log.error, .log.debug, etc) seems crucial. 

Changing the way the logger is called involves a lot of changes to a lot of files.

But @ngoldman what about in the meantime (before any wholesale changes are made) we set Winston to use stdout and stderr? that way the mechanisms for log aggregations (fluentd or whatever) can be built and understood.

**Comment by dbouwman** [comment]
@ajturner @dmfenton we had been sending harvester logs to stderr/stdout (a la PM2) but apparently @jwieringa does not have the infrastructure setup to collect that - thus we are still pumping things to files.

**Comment by jwieringa** [comment]
+1 for stderr/stdout and control over log level via ENV.

A nice win would be the ability to modify the log formatter (Syslog, Logstash, logfmt, etc.).

**Comment by dmfenton** [comment]
I think this is resolved via https://github.com/koopjs/koop-logger we can make improvements from there
