### ISSUE TITLE
Feature request: Add support for GeoRSS

### ISSUE THREAD

**Issue by juliekdang** [koopjs/koop#294]
I know, I know... it's not like the [interest in GeoRSS](https://www.google.com/trends/explore?q=geojson,geoRSS) is growing. But we need to support legacy applications that are expecting GeoRSS. Plus, it appears to be [supported by the GDAL](http://www.gdal.org/ogr_formats.html).

**Comment by dmfenton** [comment]
Hi Julie,

In order to support GeoRSS you would need to add support for the format to https://github.com/koopjs/GeoXForm
 - Add a test in index: https://github.com/koopjs/GeoXForm/blob/master/test/index.js
 - Add a test in ogr-cmd: https://github.com/koopjs/GeoXForm/blob/master/test/ogr-cmd.js

Once GeoXForm supports the format, koop-agol will automatically support it if the request is made. If you need some help with GeoXForm we can move the conversation over there. When GeoXForm supports the format we can work on cleaning up the Koop-Agol docs and get that stood up to test.

**Comment by jgravois** [comment]
i decided to take a crack at this this morning and it wasn't too bad.

koopjs/GeoXForm#7

**Comment by dmfenton** [comment]
@jgravois's PR was merged in. Once I cut a release over there, I'll update a demo version of Koop-AGOL that I have running so we can see some datasets in action.

**Comment by juliekdang** [comment]
Thanks guys

**Comment by rgwozdz** [comment]
Take a look at https://github.com/koopjs/koop-output-rss.
