### ISSUE TITLE
Server error with using date filter

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop#313]
{
error: "Unrecognized AST node: { "type": "timestamp", "value": "2018-02-18 23:56:59", "columnNode": { "type": "column_ref", "table": null, "column": "timestamp" } }"
}

I am getting a strange error when using the date filter. My query works fine in the custom provider I am writing, meaning I get valid geojson and send it back to koop core, but during the process the rest service throws the error above.  I am having trouble debugging because the issue is not in the provider,  Any thoughts?

**Comment by keithfraley** [comment]
let me clarify, I am using getting back valid geojson from the provider, but when I use filter on a datetime field (portal,AGOL) I get this ATS error

**Comment by rgwozdz** [comment]
@keithfraley - just to clarify, you have authored a new provider and are using it to provide data to AGOL via Koop.  One of the properties in your data is `timestamp`, and you are attempting to use the AGOL UI to filter by that property, but then you receive the AST.  Correct?

**Comment by keithfraley** [comment]
We have written a provider for elasticsearch in koop.  We serve that using
Koop as an esri featureservice.

When we test in agol or portal everything works except the time filter.

We have tested our provider and it is bringing back valid geojson but for
some reason the koop core rejects the geojson dataset with the ats node
error.

Regards
Keith

**Comment by keithfraley** [comment]
Additional logging leads me to believe that it might be a milliseconds issue

**Comment by gwright** [comment]
We are having the same problem and I've narrowed it down to the fact that winnow doesn't seem to support timestamp literals. https://github.com/koopjs/winnow/blob/cfa88c7813f589032e4a1ed79590f14389d2d5a6/src/where.js#L115

**Comment by gwright** [comment]
When we declare a field as a Date (via `metadata.fields`) in our provider is shows up in the FeatureService metadata as 'esriFieldTypeDate'.  When we try to query on this field via the web map filter interface the value gets represented as a timestamp literal (`timestamp '2018-03-01 01:02:03'`).  It seems as though this gets parsed correctly by the `flora-sql-parser` into a timestamp AST node, but winnow doesn't know how to deal with it.

So our questions are:
* Is this intended to work or is it just unimplemented functionality?
* Should we be declaring the field differently so that the filter UI and koop will play nice?

**Comment by gwright** [comment]
I've created a pull request for winnow that adds support for timestamp and BETWEEN syntax: koopjs/winnow#64.  Not sure why we were seeing the timestamp syntax as the tests for winnow seem to suggest a different expected syntax from ESRI tools.

**Comment by rgwozdz** [comment]
Thanks for the contribution.  Merged PR https://github.com/koopjs/winnow/commit/dfffbe234888a4876496b963b9b8429ac58c0317 and released in [winnow v1.13.0](https://github.com/koopjs/winnow/releases/tag/v1.13.0)
