### ISSUE TITLE
Serve Koop over HTTPs

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop#325]
Hi there!,

I wanted to serve Koop using HTTPs and tried to find some documentation on how to do it. I think the only way is to change the `server.js` to listen on 443 and use a private.pem and public.pem, right?

If that the casi I would suggest an enhancement on the docs and/or the code itself to be able to start the server with additional params to use https.

Cheers! // thx to @slibby for his help on this :)

**Comment by rgwozdz** [comment]
I think this is somewhat outside the scope of Koop itself has more to do with deployment environment and server configuration - there are lots of different ways one would implement HTTPs on your stack.  

Normally I'd not do it by having koop listen to 443.  Instead, I would have a web-server like Nginx listening to those ports.  For requesst coming in on 443, Nginx handles checking of the SSL certificate and then forwards the request onto the port that koop is listening on [see Nginx docs](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).  If a request comes in on port 80, you have Nginx redirect to HTTPS/443.

**Comment by hhkaos** [comment]
Thanks Rich, so don't you think it could make sense to add an extra bullet point in the section "[Extra](http://koopjs.github.io/docs/)" about deployment over https?

P.S: my devops skills are close to 0 as you can notice... and it could helpful for people like me ;P

**Comment by rgwozdz** [comment]
I think its more of a general aspect of deploying any server-side API, and there's lots of variations on how to implement depending on the deployment stack.  I guess we could put an example of what I mentioned with Nginx, but it would only apply to Nginx users.  Definitely open to PRs if you have something specific in mind to add.

**Comment by hhkaos** [comment]
Sorry rich for taking so long to answer, I have had a bunch of emails/requests lately.

>  I guess we could put an example of what I mentioned with Nginx, but it would only apply to Nginx users

That would be useful yes, maybe we could tags this issue as a "help wanted". 

Another option would be just add to the doc a short explanation as you did here to explain that this is out of the scope of the documentation, and instead of adding an example add a list of links to different tutorials on: How to setup HTTPS on different web servers and how to forward/proxy requests on each of them (Nginx, IIS, Apache,...). Does it make sense?

**Comment by mlewis22** [comment]
Would it not be easier to just add SSL support using self signed certs via express? Considering many services default to HTTPS now it seems like a sensible option. 

Otherwise it sounds like your suggesting that koop should only be used behind a web server using something like iisnode. If so i definitely think that should be made clearer.

**Comment by rgwozdz** [comment]
It is completely reasonable to run Koop (or any Node app) without a web server like Nginx.  I was only relaying how I do my own deployments with SSL.  In everyday practice, I run my Node apps behind Nginx for performance reasons that you may or may not want or need to address ([see here](https://www.nginx.com/blog/5-performance-tips-for-node-js-applications/)).  Additional, I find the implementation of SSL on Nginx with Let's Encrypt's cert bot to be painless.  But again, your situation is likely different so perhaps adding your HTTPs support via Express is the best way forward for you.
Generally though, this is more of a question about how one implements SSL for Express apps, rather than how you implement SSL for Koop in particular.  You really can do it however you think is best for your situation.

I'm still committed to documenting different ways of supporting HTTPs - but again, given that it's more a question of how one does HTTPs with Express rather than Koop specifically, it hasn't been a priority for addition to our doc site.  We would definitely be happy add contributions to our docs if you want to PR an example of how you prefer to do HTTPs on your Express apps.

You could also consider doing a PR or issue on the Koop-CLI repo (cc @haoliangyu) - perhaps we could add an option to support HTTPs via Express when auto-generating a Koop app's server.js.

**Comment by JoanPere** [comment]
Hi there!
I find in this [link]( https://timonweb.com/posts/running-expressjs-server-over-https/ ) where there are the code to run express in https.

You will need to [generate de SSL certificates ](https://flaviocopes.com/express-https-self-signed-certificate/) in node: openssl req -nodes -new -x509 -keyout server.key -out server.cert
