### ISSUE TITLE
field statistic question

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop#329]
In using the elasticsearch provider I noticed that values brought on return are only the stats of the first set of results.  If the limit is set to 1000 records returned then you are only get the stats of that 1000 records.

My question is this, is that an issue that is handled at the provider level or at the fs level?  How can I modify the query on the backend to get stats on all records?

**Comment by rgwozdz** [comment]
Hi @keithfraley - thanks for reaching out. I'm glad you brought this up.  You're correct - the data is being reduced by either the `limit` value (if set in request) or the `maxRecordCount`.  Stats should not be calculated like this, so I think you've found a bug.  In the short term, you can work around this by setting the `maxRecordCount` metadata property in your provider to a value that will be equal to or larger than your full record set.

But I think we need to change Winnow so that aggregate queries do calculations over the full record set delivered from the provider.  I will add an issue to the Winnow repo.

**Comment by rgwozdz** [comment]
Here's the Winnow issue: https://github.com/koopjs/winnow/issues/96

**Comment by keithfraley** [comment]
Thanks for the quick response Rich, the challenge is that when working with datasets much larger than a reasonable max record count I dont see that you will have much choice other than to go through the provider. 

Perhaps one enhancement would be the option to calc field stats at a provider level?

**Comment by keithfraley** [comment]
Thanks! I will have a look

**Comment by rgwozdz** [comment]
After a deeper dive, I have determined that there isn't any bug here, at least using the providers I am currently using. You can add a `limit` or a `resultRecordCount` to the request and change its value, but I find the `outStatistics` are calculated over the entire record set delivered to koop from the provider.  Adding `limit` or a `resultRecordCount` does add a `LIMIT` to the SQL query in winnow, but like standard SQL, the `LIMIT` fragment doesn't appear to affect calculations.
