### ISSUE TITLE
suppress metadata/feature property warnings or test for NaN?

### ISSUE THREAD

**Issue by mpayson** [koopjs/koop#330]
I'm working with a dataset that has a good number of missing values. This causes Koop to throw
> `WARNING: requested provider's metadata field... not found in feature properties`

on every query. Is there a way to silence or modify these warnings?

A couple examples: 
* integer field with undefined values
  * [detect type](https://github.com/koopjs/FeatureServer/blob/master/src/utils.js#L50) returns `Double` for `NaN` or `String` for `null`/`undefined`
  * [metadata/feature property check](https://github.com/koopjs/FeatureServer/blob/master/src/query.js#L127) throws a warning because `field.type = Integer` and `featureField.type = Double | String`
* date field with undefined values
  * winnow.query returns `NaN` for invalid dates
  * [detect type](https://github.com/koopjs/FeatureServer/blob/master/src/utils.js#L50) returns `Double` for `NaN`
  * [metadata/feature property check](https://github.com/koopjs/FeatureServer/blob/master/src/query.js#L127) throws a warning because `field.type = Date` and `featureField.type = Double`

Since the metadata/feature property check is _okay_ with `featureField.type = Integer` and `field.type = Date | Double`, my warnings could be fixed if detectType returns `Integer` for NaN, but I'm not sure if this would have unintended side effects.

```javascript
function detectType (value) {
  var type = typeof value

  if (type === 'number') {
    return Number.isInteger(value) || isNaN(value) ? 'Integer' : 'Double'
  } // ...
}
```
 
thanks!

**Comment by rgwozdz** [comment]
@mpayson thanks for reporting this.  Seems like at a minimum these warnings should only be issued when `NODE_ENV !== 'production'`.   Would that be enough for your use case?  We put in the warnings because ArcGIS clients can break when the `fields` array elements have data types that do not match the data types in the feature properties.

I think the only unintended consequence of your proposal is that when there is a mismatch between the `fields` data-type and feature properties data type, and that mismatch causes breakage on ArcGIS client, a developer wouldn't get the warning as a clue for diagnosing the problem.

**Comment by mpayson** [comment]
@rgwozdz sounds good, that would fit my use case, thanks!

**Comment by rgwozdz** [comment]
@mpayson FYI, just back from holiday leave.  This is still on my radar.

**Comment by rgwozdz** [comment]
@mpayson - FeatureServer release [2.15.2](https://github.com/koopjs/FeatureServer/releases/tag/v2.15.2) will suppress warnings when `NODE_ENV === 'production'` or `KOOP_WARNINGS === 'suppress'`.  `yarn upgrade` should get you this latest version of FeatureServer.

**Comment by rgwozdz** [comment]
There are still a few warnings in the Winnow dependency.  Will address those in same manner.

**Comment by rgwozdz** [comment]
Added warning suppression to Winnow 1.16.4.
