### ISSUE TITLE
Is there a way to turn off pagination via resultOffset, resultRecordCount?

### ISSUE THREAD

**Issue by simon-fisher** [koopjs/koop#357]
Is there a way to turn off pagination via resultOffset, resultRecordCount at the Koop filter so I can pass through and implement in my own provider?

**Comment by rgwozdz** [comment]
Hello @simon-fisher - yes there is a way.  Implement in your own provider and then add a `filtersApplied` object to your geojson in the `getData` method:

```
// get geojson from remote API...

// implement your own pagination

// Inform Koop that you have already applied pagination
geojson.filtersApplied = {
  offset: true,
  limit: true
}

// pass geojson to callback
```

`filtersApplied` is somewhat documented in [FeatureServer](https://github.com/koopjs/FeatureServer#featureserverroute) but we'll add it to the main docs soon.

**Comment by haoliangyu** [comment]
@rgwozdz Is it possible to use the "after" function to add the filter setting for existing providers?

**Comment by rgwozdz** [comment]
Yes, absolutely.  Though I had assumed he was authoring a new provider which always does the pagination itself.  In a case like that, it seems like you would want to do the filtering and filtersApplied setting in the same place, rather than leave setting “filterApplied” to the registration options.  I’m working up the docs for the “before” and “after” functions – that should help people decide the best option.

Rich Gwozdz | Software Engineer
Esri
rgwozdz@esri.com
