### ISSUE TITLE
Koop Cache: files are not deleted when cache expires

### ISSUE THREAD

**Issue by mcasamayorpolo** [koopjs/koop#359]
When files in cache have ttl specified in the options, koop cache memory doesn't delete these items when time has expired.

**Comment by rgwozdz** [comment]
This is fixed in latest Koop.  We have moved to an LRU cache with expiration.  Items are ejected from the cache when it gets filled.  The least recently used entry is the first to be ejected.  In addition, if an item from the cache is retrieved and it's found to be expired, it will be ejected from the cache at that time.
