### ISSUE TITLE
koopjs/koop vs koopjs/koop-core is confusing

### ISSUE THREAD

**Issue by gavinr** [koopjs/koop#366]
Sharing my experience as a new developer user:

- saw on [the blog](https://koopjs.github.io/blog/2020/07/01/koop-v-4-0-0/) that v4.0.0 is out. 
- clicked on the "GitHub" icon in the nav, brought me to https://github.com/koopjs
- saw that `koopjs/koop` was pinned, assumed that's the main place to look for the releases. 
    ![image](https://user-images.githubusercontent.com/209355/88928716-a97a0780-d268-11ea-9087-dbca3037bb21.png)

- latest release is 3.2 in 2017 - huh?
    ![image](https://user-images.githubusercontent.com/209355/88928793-c1518b80-d268-11ea-8ce4-b304e5a5b4ef.png)
- Readme says "New @ version 3" - huh??
    ![image](https://user-images.githubusercontent.com/209355/88928844-d4645b80-d268-11ea-9bca-194e3c9afd4c.png)

I then manually looked up koop on npmjs.com, eventually saw that it does have v4.0.0 as the latest version (as the blog post says) and links to github.com/koopjs/koop-core

I'm not sure how to resolve this - do we still want `koopjs/koop` to be the main repo for the project, or is `koopjs/koop-core` filling that role now? If we're just using `koopjs/koop` for issues, maybe we should clear out the readme and releases on this repo and just link to `koopjs/koop-core` or the documentation site? Or if `koopjs/koop-core` is the main repo, maybe pinning that instead on the org page? Or maybe both repos are still used and they are under different release schedules?

**Comment by rgwozdz** [comment]
Hey @gavinr - I really appreciate this.  You're totally right - this is confusing.  This structure was put in place before I came on to the project and the folks that thought it up are no longer part of the maintainer team.  I think the idea was that Koop, due to it's plugin architecture is a collection of repos, and not just koop-core.  koopjs/koop really just serves as a stand-in for a centralized place for issues - so for example, you're new to Koop, you have a bug, but it's really not clear if it's koop-core, FeatureServer, winnow, or one of the providers.

I like your idea of clearing the readme and releases from koopjs/koop.  I also think we should clear all the repo pointers - it's not necessary anymore, now that we have a better doc site.  We ca use this repo for issues that user's don't know where else to put.

**Comment by gavinr** [comment]
Sounds good - thanks for the response!

**Comment by rgwozdz** [comment]
Changes made.

**Comment by gavinr** [comment]
Thanks!
