### ISSUE TITLE
HTTPS Feature is not working

### ISSUE THREAD

**Issue by rprasanth49** [koopjs/koop#376]
Hi,

I have developed an app with Koop JS and created a custom provider. Everything is working however the URL workings only on HTTP. So, I have created PEM files for SSL and CA certificates and placed them in the app folder. Then run the 'Koop Serve' command with SSL Cert and SSL key attributes. However, the link works on HTTP, not on HTTPS. So, to make sure there is no issue with the certificate, I have created a simple NODE JS app with an HTTPS node js module. Everything is working fine with CA and SSL certificate files. 

So, just wanted to see if I am missing anything here to get HTTPS working on Koop JS applications. Below links are I used as a reference. Let me know if you want me to share any screenshots or code files for this issue.

https://koopjs.github.io/blog/2021/01/19/koop-cli-v1-1-0-release/

https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTPS-server/

Tagging @haoliangyu to see if I can get some help here.

**Comment by rprasanth49** [comment]
I have posted the same question on the ESRI community page and looks like one of the users also had the same issue. The user posts the solution and here is the link for the same.

https://community.esri.com/t5/developers-questions/https-feature-is-not-working-in-koop-js/m-p/1069549#M5912

**Comment by haoliangyu** [comment]
Creating an HTTPS server with nodejs needs to modify how the app server is set up (as in [here](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTPS-server/)). If your project is a Koop app, the HTTPS feature won't work because Koop CLI doesn't modify your code from an HTTP server to an HTTPS server. This feature is added to create a test HTTPS server for plugin projects. It looks like the documentation is not clear about this and I will update.

If you are developing a Koop app and make it a nodejs HTTP server, you have to manually update your server code. However, I don't think this solution is scalable and decide not to add that to the app template inside Koop CLI.

**Comment by rgwozdz** [comment]
Consider using a reverse proxy for production: https://medium.com/intrinsic-blog/why-should-i-use-a-reverse-proxy-if-node-js-is-production-ready-5a079408b2ca

**Comment by rprasanth49** [comment]
Thank you. I will take note it.
