### ISSUE TITLE
Problem with Zoom to in ESRI Portal Map Viewer

### ISSUE THREAD

**Issue by freddiesia** [koopjs/koop#385]
I have a Feature Service in ESRI Portal hosted via koop GEOJSON. All works ok except the 'Zoom to' function when view the data in 'Open in Map Viewer'. It zooms to the weird extent. The extent has been set in the geoJSON. Please let me know if there is any other information you may need.
Test URL: https://alpha.portal.spatial.nsw.gov.au/geoserver/cadnsw/wollondilly/FeatureServer/0
I have directed this issue to ESRI Support but they advised that we report this issue in github.

**Comment by rgwozdz** [comment]
Hello @freddiesia - It's very difficult to help with this without a link to the Map Viewer that includes the noted Koop service.  Can you send a link?

**Comment by rgwozdz** [comment]
@freddiesia are you still having the noted issue?

**Comment by bsvensson** [comment]
In the new Map Viewer - https://www.arcgis.com/apps/mapviewer/index.html?url=https://alpha.portal.spatial.nsw.gov.au/geoserver/cadnsw/wollondilly/FeatureServer/0 - it's not zooming to the right place because the extent query, https://alpha.portal.spatial.nsw.gov.au/geoserver/cadnsw/wollondilly/FeatureServer/0/query?f=json&returnExtentOnly=true&returnCountOnly=true&outSR=102100&spatialRel=esriSpatialRelIntersects&where=1%3D1, returns incorrect data.

`{"count":721,"extent":{"xmin":16754005.476764813,"ymin":-4069034.6763877873,"xmax":16804130.149912428,"ymax":-4013753.19865697,"spatialReference":{"wkid":4326,"latestWkid":4326}}}` 
Notice in that koop response that the coordinates are in web mercator, but the spatial reference says 4326 (when it should be "102100"). That's why the "Zoom to" doesn't work.

**Comment by freddiesia** [comment]
Thank you.

**Comment by rgwozdz** [comment]
Closing as inactive.
