### ISSUE TITLE
Call for enhancement/feature requests

### ISSUE THREAD

**Issue by rgwozdz** [koopjs/koop#529]
We're preparing to debate the roadmap for the coming year and looking for any input on enhancements and feature requests.  Please add yours as a new issue and I will tag it as appropriate.  We hope to have a roadmap settled by mid-summer.

**Comment by AvidDabbler** [comment]
Its been a while since I looked at the docs, but I think my big issue with it was figuring out how to run server side envelope queries. Would be nice to have some best practices or a method to be able to do the filtering that way.

For reference I was using AWS Athena, pulling in all of the data and then filtering, being able to just have the data with the envelope would have been nice and having something like a query builder would have been beneficial. This could all be user error or me not reading the docs well enough.

**Comment by jmburns** [comment]
Please add support for PBF output from the built-in feature server output.

**Comment by internationalmapping** [comment]
Support for updateFeatures. If it's feasible, we'd be happy to assist.

**Comment by AvidDabbler** [comment]
Prisma integration whenever they get around to adding geo support

**Comment by internationalmapping** [comment]
> @internationalmapping
> 
> > Support for updateFeatures. If it's feasible, we'd be happy to assist.
> > Yes, it is feasible, we need to decide on standard provider methods and then update/refactor FeatureServer.

If you can provide a rough outline, perhaps I could prototype something? Happy to discuss either way.

**Comment by AvidDabbler** [comment]
I guess my thought was that if you built with prisma you would gain the
ability to connect to lots of different types of databases rather than
making something that would work with just one type of database.
The allure for prisma is the type safety as well. I love being able to take
a look at the types and keep me on the guard rails.
I guess it was building on the updateFeatures request as well. If you could
setup koop to take in a prisma schema you could create multiple services
that could talk to one another and quickly build out update features.
You could also better handle the type safety of the url parameters for
advanced queries rather than just relying in taking in just strings.

So lots of type safety, built for multiple db's at the same time, tie into
the existing update, upsert, findMany functions that exist, and better
safety for url params.

**Comment by rgwozdz** [comment]
With Koop's plugin architecture, connecting to a database is the job of individual provider-plugins, so nothing stopping you from using any ORM there. But not all providers connect to a database; some are just remote APIs that wouldn't support Prisma. Also, output-plugins like featureserver, which would be doing the `updateFeatures` operation need to be completely decoupled from things like ORMs, because they might connect to a provider that doesn't support the ORM.  If not, you have to start making rules that all providers need a particular ORM, so that the methods are always there for output-plugins to use.  And as noted early, some providers connect to things that aren't able to support ORMs.
