### ISSUE TITLE
PBF Output errors with "Unknown geometry type" when geojson.filtersApplied.all is set to true

### ISSUE THREAD

**Issue by jag-eagle-technology** [koopjs/koop#984]
As per title, 

If I provide geojson to the output geoservices plugin with the filltersApplied object all field set to true and request PBF, I receive the error "Unknown geometry type". Setting geometry, where, offset, limit and projection individually does not cause this issue.

**Comment by rgwozdz** [comment]
Thanks for reporting this @jag-eagle-technology.

**Comment by rgwozdz** [comment]
@jag-eagle-technology - which Koop release are you using?  I am having trouble reproducing this, and we already pushed a patch for a similar error:

https://github.com/koopjs/koop/pull/945

That would have gone out in koop-core 10.3.7;  can you update to latest release if you haven't already ([@koopjs/koop-core@10.4.5](https://github.com/koopjs/koop/releases/tag/%40koopjs%2Fkoop-core%4010.4.5) and confirm you still get the error reported above?

**Comment by jag-eagle-technology** [comment]
I'm using the latest version. Here's a basic reproduction example:

https://github.com/jag-eagle-technology/koop-pbf-issue

**Comment by rgwozdz** [comment]
No, you are spot on.  It's a bug you have found.  I just overlooked something while I was trying to reproduce.  Thanks for the details! We'll sort it out and get a patch shortly.

**Comment by rgwozdz** [comment]
@jag-eagle-technology 

Ok, the good news is that this could maybe be viewed as not so much a bug, but maybe just a doc change.
 
The issue is that when you go `filtersApplied: { all: true }`, Koop doesn't pipe the provider data through any post-provider filtering _or transforms_; including the the transform from GeoJSON to Esri JSON.  The PBF encoder expects Esri JSON, but it ends up getting GeoJSON, and then throws the error.
 
This is sort of a problem with what the name `filtersApplied` implies and our docs. It suggests that the only thing happening in that stage is "filtering" and if you have done that already in your provider you can skip everything with `all`. But that isn't true - that stage is also where the GeoJSON to Esri JSON conversion occur, which is required for FeatureServer routes. (I think this transform was originally executed in filtering stage to avoid looping through all the data).  When `filtersApplied` is instead set with individual properties like:
 ```js
geojson.filtersApplied = {
        geometry: true,
        where: true,
        offset: true,
        limit: true,
        projection: true,
      }
```

the GeoJSON is still piped through the noted post-processing stage, and while the filtering is skipped, the conversion is still made.
 
In the short-term, `filtersApplied` should not use the `all` property, but instead set each individual property to `true`.  Honestly, it's probably best to eliminate the use of `all`.

**Comment by jag-eagle-technology** [comment]
Makes sense. I'd tried querying for JSON directly - but found the transform (Esri JSON not Koop) information was dropped so the geometry wasn't valid.
